version: '3.7'

services:
  mash-client:
    container_name: mash-client
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    ports:
      - "8000:8000" # web
      - "8080:8080" # mash-term
      - "8081:8081" # mash-editor
    volumes:
      - ../:/projects
    working_dir: /projects/client
    tty: true
