version: '3.7'

services:
  mash:
    container_name: mash
    build:
      context: .
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - .:/projects
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    tty: true
