version: '3'

services:
  mash:
    container_name: mash
    build:
      context: .
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - .:/projects
    tty: true
  server-web-mongo:
    container_name: server-web-mongo
    image: mongo:4.2.2
    ports:
      - "27017:27017"
    volumes:
      - v-server-web-mongo:/data/db
    tty: true
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    tty: true

volumes:
  v-server-web-mongo:
