version: '3.7'

x-go-service-default: &go-service-default
  build:
    context: ./docker
    dockerfile: Dockerfile.golang
  volumes:
    - .:/backend
  tty: true
  command: /bin/bash

x-mongo-default: &mongo-default
  image: mongo:4.2.2
  tty: true

services:
  mash-s-frontend:
    <<: *go-service-default
    container_name: mash-s-frontend
    working_dir: /backend/services/frontend
  mash-s-frontend-mongo:
    <<: *mongo-default
    container_name: mash-s-frontend-mongo

  rabbitmq:
    image: rabbitmq:3.7-alpine
    container_name: mash-rabbitmq
    tty: true
