// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "frontend/graph/model"
)

// SubscriptionResolver is an autogenerated mock type for the SubscriptionResolver type
type SubscriptionResolver struct {
	mock.Mock
}

// TodoAdded provides a mock function with given fields: ctx, userID
func (_m *SubscriptionResolver) TodoAdded(ctx context.Context, userID string) (<-chan *model.Todo, error) {
	ret := _m.Called(ctx, userID)

	var r0 <-chan *model.Todo
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan *model.Todo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *model.Todo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
