version: '3.7'

services:
  js-client:
    volumes:
      - v-sync-mash-node_modules:/projects/node_modules
      - v-mash-yarn:/usr/local/share/.cache/yarn

volumes:
  v-mash-yarn:
  v-sync-mash-node_modules:
    external: true
