name: client-deploy-web

on:
  push:
    branches:
    - master
    paths:
    - "client/packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      wd: ./client
    steps:
    - uses: actions/checkout@v1

    - run: docker-compose build
      working-directory: ${{ env.wd }}
    - run: docker-compose up -d
      working-directory: ${{ env.wd }}
    - run: docker-compose exec -T mash-client bash -c 'yarn bootstrap && yarn fulltest'
      working-directory: ${{ env.wd }}

    - run: ./scripts/deploy-web.sh
      working-directory: ${{ env.wd }}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
