name: mash

on:
  push:
    branches:
    - master
    paths:
    - "client/packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cd client
    - run: docker-compose build
    - run: docker-compose up -d
    - run: docker-compose exec -T mash-client bash -c 'yarn bootstrap && yarn build'
    - run: ./scripts/deploy-web.sh
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
