name: mash

on:
  push:
    branches:
    - master
    # paths:
    # - "client/packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: cd ./client
    - run: pwd
    - run: ls
    - run: ./docker-compose.sh build
    - run: ./docker-compose.sh up -d
    - run: ./docker-compose.sh exec -T mash-client bash -c 'yarn bootstrap && yarn fulltest'

    - run: ./scripts/deploy-web.sh
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
