name: mash

on:
  push:
    paths:
    - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    env:

    steps:
    - uses: actions/checkout@v1

    - name: test
      run: |
        docker-compose build mash
        docker-compose up -d mash
        docker-compose exec -T mash bash -c 'npx lerna bootstrap && yarn fulltest'
