name: mash

on:
  push:
    branches-ignore:
    - master
    paths:
    - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: test
      run: |
        docker-compose build mash
        docker-compose up -d mash
        docker-compose exec -T mash bash -c 'yarn bootstrap && yarn fulltest'
